services:
  - type: web
    name: epub-converter
    env: python
    buildCommand: pip install -r requirements-render.txt
    startCommand: gunicorn app_render:app --host 0.0.0.0 --port $PORT
    plan: free
    healthCheckPath: /health
    envVars:
      - key: FLASK_ENV
        value: production
      - key: PYTHON_VERSION
        value: 3.11.9
